FROM python:3.11.11-alpine3.21 

WORKDIR /app

COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt
RUN pip install -r requirements.txt

COPY . .

EXPOSE 5000

# Health check (optional)
HEALTHCHECK CMD curl --fail http://localhost:5000/ || exit 1

#  Development
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]

#  Production
# CMD ["gunicorn", "--reload", "-k", "uvicorn.workers.UvicornWorker", "-w", "4", "-t", "100", "-b", "0.0.0.0:5000", "app:app"]
